# parameters
nc: 6  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

#这一个yaml文件，是将所有的elan-H都换成了elan

# anchors
anchors:
  - [10,13, 16,30, 332,23]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16

# yolov7 backbone
backbone:
  # [from, number, module, args]
  [
   [-1, 1, Conv, [16, 3, 1]],  # 0      640
   [-1, 1, Conv, [16, 3, 2]],  # 1-P1/2     320  
   [-1, 1, Conv, [16, 3, 1]],  #2              #320 
   [-1, 1, Conv, [64, 3, 2]],  # 3-P2/4       160
   [-1, 3, c2f, [256, True]],   #4
   [-1, 1, MP, []],            #5
   [-1, 1, Conv, [64, 1, 1]],  #6
   [-3, 1, Conv, [64, 1, 1]],  #7
   [-1, 1, Conv, [64, 3, 2]],    #8                #80
   [[-1, -3], 1, Concat, [1]],  # 9-P3/8  
   [-1, 6, c2f, [256, True]],   #10
   [-1, 1, MP, []],     #11
   [-1, 1, Conv, [128, 1, 1]],   #12
   [-3, 1, Conv, [128, 1, 1]],  #13
   [-1, 1, Conv, [128, 3, 2]],     #14               #40
   [[-1, -3], 1, Concat, [1]],  # 15-P4/16  
   [-1, 6, c2f, [512, True]],    #16
   [-1, 1, MP, []],             #17
   [-1, 1, Conv, [256, 1, 1]],   #18
   [-3, 1, Conv, [256, 1, 1]],   #19
   [-1, 1, Conv, [256, 3, 2]],   #20               #20
   [[-1, -3], 1, Concat, [1]],  # 21-P5/32  
   [-1, 3, c2f, [512, True]],    #22
  ]

# yolov7 head
head:
  [[-1, 1, SPPCSPC, [512]], # 23                
   [-1, 1, Conv, [128, 1, 1]],   #24
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],  #25        #40
   [37, 1, Conv, [128, 1, 1]], # route backbone P4    26
   [[-1,-2], 1, Concat, [1]],  #27
   [-1, 3, c2f, [256, True]],   #28
   [-1, 1, Conv, [64, 1, 1]],   #29
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],         #30
   [24, 1, Conv, [64, 1, 1]], # route backbone P3     31
   [[-1,-2], 1, Concat, [1]],  #32
   [-1, 3, c2f, [256, True]],     #33
   [-1, 1, MP, []],    #34
   [-1, 1, Conv, [128, 1, 1]],   #35
   [-3, 1, Conv, [128, 1, 1]],   #36
   [-1, 1, Conv, [128, 3, 2]],   #37         #40
   [[-1, -3, 63], 1, Concat, [1]],  #38
   [-1, 3, c2f, [256, True]],         #39
   [75, 1, RepConv, [128, 3, 1]],    #40
   [88, 1, RepConv, [512, 3, 1]],    #41
   [[89,90], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5 ）      52
  ]

#-----------分割头------------#
rustseg:
  [[ 50, 1, nn.Upsample, [None, 2, 'nearest']],    #43
   [-1, 1, Conv, [128, 3, 1]],                        #44
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],       #45
   [-1, 1, Conv, [64,3,1]],                          #46
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],       #47
   [-1, 1, Conv, [32, 3, 1]],                       #48
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],          #49
   [-1, 1, Conv, [16, 3,1]],                           #50
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],          #51
   [-1,1,C2f,[8,False]],                         #52
   [-1, 1, Conv, [2,3,1]],                           #53       
  ]