# parameters
nc: 6  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

#这一个yaml文件，是将所有的elan-H都换成了elan

# anchors
anchors:
  - [10,13, 16,30, 332,23]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16

# yolov7 backbone
backbone:
  # [from, number, module, args]
  [
   [-1, 1, Conv, [16, 3, 1]],  # 0      640
   [-1, 1, Conv, [16, 3, 2]],  # 1-P1/2     320  
   [-1, 1, Conv, [16, 3, 1]],                #320 
   [-1, 1, Conv, [64, 3, 2]],  # 3-P2/4       160

          #ELAN
   [-1, 1, Conv, [256, 1, 1]],              #160
   [-2, 1, Conv, [256, 1, 1]],             #160
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],   # 11
          #MP1
   [-1, 1, MP, []],
   [-1, 1, Conv, [64, 1, 1]],
   [-3, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 2]],                    #80
   [[-1, -3], 1, Concat, [1]],  # 16-P3/8  
          #ELAN
   [-1, 1, Conv, [64, 1, 1]],
   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],  # 24
           #MP1 
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],                    #40
   [[-1, -3], 1, Concat, [1]],  # 29-P4/16  
           #ELAN
   [-1, 1, Conv, [128, 1, 1]],
   [-2, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [512, 1, 1]],  # 37
   
          #MP1  
   [-1, 1, MP, []],
   [-1, 1, Conv, [256, 1, 1]],
   [-3, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 2]],                     #20
   [[-1, -3], 1, Concat, [1]],  # 42-P5/32  
          #ELAN
   [-1, 1, Conv, [128, 1, 1]],
   [-2, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [512, 1, 1]],  # 50
  ]

# yolov7 head
head:
  [[-1, 1, SPPCSPC, [512]], # 51              
           #UP
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],         #40

   [37, 1, Conv, [128, 1, 1]], # route backbone P4
    
   [[-1,-2], 1, Concat, [1]],  #55
            #ELAN
   [-1, 1, Conv, [64, 1, 1]],
   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],  # 24

             #UP
   [-1, 1, Conv, [64, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],         #65

   [24, 1, Conv, [64, 1, 1]], # route backbone P3
   
   [[-1,-2], 1, Concat, [1]],  #67
          #ELAN
   [-1, 1, Conv, [64, 1, 1]],
   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],  # 24
  
  # zheshi MP2+cat  
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],              #40
   [[-1, -3, 63], 1, Concat, [1]],  #79

   #  ELAN
   [-1, 1, Conv, [64, 1, 1]],
   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],  # 24

   [75, 1, RepConv, [128, 3, 1]],  
   [88, 1, RepConv, [512, 3, 1]],

   [[89,90], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5 ）      91
  ]

#-----------分割头------------#
rustseg:
  [[ 50, 1, nn.Upsample, [None, 2, 'nearest']],    #92
   [-1, 1, Conv, [128, 3, 1]],                        #93
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],       #94
   [-1, 1, Conv, [64,3,1]],                          #95
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],       #96
   [-1, 1, Conv, [32, 3, 1]],                       #97
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],          #98
   [-1, 1, Conv, [16, 3,1]],                           #99
   [ -1, 1, nn.Upsample, [None, 2, 'nearest']],          #100
   [-1,1,C3,[8,False]],                         #101
   [-1, 1, Conv, [2,3,1]],                           #102       
  ]